language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --ignore-platform-reqs

script:
  - mkdir -p build/logs
  - php ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry php ./vendor/bin/coveralls

sudo: false
